# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ad09d880047051445c94a75a8c11a026ede3ff3f6282bb4c68f0bb47e9d5e12b8feecc1c8498fa946e1a12cb3eb5bc7d95bea91867ddbdf0b2423074acf9541

test:
  secret_key_base: 3f5eeda2b4ed410f4dac80cf38a33eee934bec4055ef7c6893552d17bfb31250041a49554b9b1115ab19a2bc23afe8d07022c5cb593a51bae7461baf535ce6dc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
