# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33b46314cf2b90919e664945199fd13cdd52a8c3c84ccf8fdb52fcf960d3c6cb28e19ae61ec1623b8ca6401772bc730adcfad6106b5acda354e7e9f0da4d969e

test:
  secret_key_base: a03e721d07b12dd37108ff48b889b1b90580f368090a0731d677e21cd435af29f37ee61dc88443c9def0d2433fd4569ea030ee2bea5339aad464e20a04af8808

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
