class RockPaperScissorsController < ApplicationController
  def new
  end

  def show
  	throw = params[:id]
  end

  #looks like you need some game logic ! 
  # I would take the entry that the user provided...ie the stuff you saved to throw, and I would 
  # compare that to a random choice generated by the computer. Ruby has a .rand method that you can
  # use to generate a random number. I would take that number and count it as the computer's choice.
  # For example, lets say the user selects paper. That link would pass a number through the url as params[:id].
  # Lets say that paper coresponds to the number 2. You can then compare the #2 with a random number from the comp,
  # and decide if #2 beats the selection the comp made.




end
