source 'https://rubygems.org'

#Core Management
gem 'rails', '4.1.8'
gem 'sqlite3'
gem 'carrierwave'
gem 'devise'

#Front End Management
gem 'sass-rails', '~> 4.0.3'
gem 'bootstrap-sass'
gem 'autoprefixer-rails'
gem 'simple_form'
gem 'font-awesome-sass'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'


#Testing  & Debugging
gem 'annotate'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

# Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
gem 'spring',        group: :development
gem 'pry'
gem 'pry-rails'
