source 'https://rubygems.org'


# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc        

#Core Management
gem 'rails', '4.1.8'
gem 'sqlite3'

#Front End Management
gem 'sass-rails'
gem 'bootstrap-sass'
gem 'autoprefixer-rails', '4.0.0'
gem 'simple_form'
gem 'font-awesome-sass'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder'

#Testing & Debugging Tools 
group :development do
  gem 'annotate'
  gem 'pry-rails'
  gem 'binding_of_caller'
  gem 'better_errors'
  gem 'pry'
  gem 'pry-byebug'
  gem 'thin'
  gem 'spring'
end

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

