# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 109bcba64288781b5483cddead562e08266543c87182e86e96ac3b33ba1c3e343cad5a616795c1845993bd598cca68d90a73be6edac01f6367adda45e896308b

test:
  secret_key_base: 2bd3127ff86f96999347e2c28070796007768c98dad5e4c19345115aceb494ba2f12bffbf7498ecaf0667eaa8aef0e5da55e65c9670ea47566cf06af13d4a989

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
