# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4616887127364e663a5fefd19717c8fcbc285a84fab1caefdece622755604f139dfb2be1dac87022e10e6e981cb6e3e05152bc5eb005aa93528b8cae8df96e83

test:
  secret_key_base: 63b5bb07cca9aeb6d0a63b8b398bde3ce4644e3c02c2df849f125dad46f9e7b88791088fc87292f653113b519e18eda42a612976b71b4b0db2132e10c3baba8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
